module DigitMap
  BLANK             = "   "
  RIGHT             = "  |"
  BOTTOM            = " _ "
  BOTTOM_RIGHT      = " _|"
  LEFT_RIGHT        = "| |"
  LEFT_BOTTOM_RIGHT = "|_|"
  LEFT_BOTTOM       = "|_ "

  ZERO = BOTTOM + LEFT_RIGHT + LEFT_BOTTOM_RIGHT
  ONE = BLANK + RIGHT + RIGHT
  TWO = BOTTOM + BOTTOM_RIGHT + LEFT_BOTTOM
  THREE = BOTTOM + BOTTOM_RIGHT + BOTTOM_RIGHT
  FOUR = BLANK + LEFT_BOTTOM_RIGHT + RIGHT
  FIVE = BOTTOM + LEFT_BOTTOM + BOTTOM_RIGHT
  SIX = BOTTOM + LEFT_BOTTOM + LEFT_BOTTOM_RIGHT
  SEVEN = BOTTOM + RIGHT + RIGHT
  EIGHT = BOTTOM + LEFT_BOTTOM_RIGHT + LEFT_BOTTOM_RIGHT
  NINE = BOTTOM + LEFT_BOTTOM_RIGHT + BOTTOM_RIGHT
  UNKNOWN = "?"
end